version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=burp_user
      - MARIADB_DATABASE=burp
      - MARIADB_PASSWORD=burp_pass
    volumes:
      - ./:/bitnami/mariadb

  myapp:
    tty: true
    image: bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=burp_user
      - DB_DATABASE=burp
      - DB_PASSWORD=burp_pass
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/app
