version: '2'

services:
  db:
    image: bitnami/mariadb:10.6
    container_name: db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=burp_user
      - MARIADB_DATABASE=burp
      - MARIADB_PASSWORD=burp_pass
    volumes:
      - ./:/bitnami/Notes

  webapp:
    tty: true
    image: bitnami/laravel:8
    container_name: webapp
    environment:
      - DB_HOST=db
      - DB_USERNAME=burp_user
      - DB_DATABASE=burp
      - DB_PASSWORD=burp_pass
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/app
